/**
 * jpeg-to-jxl: Lossless JPEG <-> JXL transcoding
 *
 * ~20% smaller files with byte-perfect JPEG reconstruction.
 * Uses libjxl's JxlEncoderAddJPEGFrame under the hood via WASM.
 *
 * Usage:
 *   import { jpegToJxl, jxlToJpeg } from 'jpeg-to-jxl';
 *
 *   const jxlBuffer = await jpegToJxl(jpegArrayBuffer);
 *   const originalJpeg = await jxlToJpeg(jxlBuffer);
 */

let _module = null;

/**
 * Lazy-load and initialize the WASM module.
 * Subsequent calls return the cached module.
 */
async function getModule() {
  if (_module) return _module;

  // The WASM module is generated by Emscripten and placed in dist/
  const createModule = (await import('./transcode.js')).default;
  _module = await createModule({
    // Locate the .wasm file relative to the JS file
    locateFile: (path) => {
      if (typeof document !== 'undefined') {
        // Browser: resolve relative to current script
        return new URL(path, import.meta.url).href;
      }
      // Node.js: resolve relative to this file
      return new URL(path, import.meta.url).pathname;
    },
  });

  return _module;
}

/**
 * Lossless JPEG to JXL transcoding.
 *
 * Repackages JPEG's DCT coefficients into JXL format without decoding
 * to pixels. The result is ~20% smaller and can be perfectly reversed
 * back to the exact original JPEG.
 *
 * @param {ArrayBuffer|Uint8Array} jpegData - Raw JPEG file bytes
 * @param {Object} [options]
 * @param {number} [options.effort=3] - Encoding effort 1-9 (higher = slower + smaller)
 * @returns {Promise<ArrayBuffer>} JXL file bytes
 * @throws {Error} If input is not a valid JPEG or transcoding fails
 */
export async function jpegToJxl(jpegData, options = {}) {
  const { effort = 3 } = options;
  const mod = await getModule();

  const input = jpegData instanceof ArrayBuffer
    ? new Uint8Array(jpegData)
    : jpegData;

  if (input.length < 2 || input[0] !== 0xFF || input[1] !== 0xD8) {
    throw new Error('Input does not appear to be a valid JPEG (missing SOI marker)');
  }

  // Allocate input buffer in WASM memory
  const inputPtr = mod._malloc(input.length);
  mod.HEAPU8.set(input, inputPtr);

  // Allocate output size pointer (size_t = 4 bytes in wasm32)
  const sizePtr = mod._malloc(4);

  try {
    const outPtr = mod._jpeg_to_jxl(inputPtr, input.length, sizePtr, effort);

    if (!outPtr) {
      throw new Error(
        'JPEG to JXL transcoding failed. Input may not be a valid JPEG, '
        + 'or it may use features not supported by the transcoder '
        + '(e.g., arithmetic coding, JPEG 2000).'
      );
    }

    const outSize = mod.HEAPU32[sizePtr >> 2];
    // Copy output to a new ArrayBuffer (so we can free WASM memory)
    const result = new ArrayBuffer(outSize);
    new Uint8Array(result).set(mod.HEAPU8.subarray(outPtr, outPtr + outSize));

    mod._jxl_free(outPtr);
    return result;
  } finally {
    mod._free(inputPtr);
    mod._free(sizePtr);
  }
}

/**
 * Reconstruct the original JPEG from a JXL file.
 *
 * Only works with JXL files that contain JPEG reconstruction metadata
 * (created via jpegToJxl, or via `cjxl input.jpg output.jxl`).
 *
 * The output is byte-identical to the original JPEG -- not just visually
 * equivalent, but the exact same file.
 *
 * @param {ArrayBuffer|Uint8Array} jxlData - JXL file bytes (with JPEG reconstruction data)
 * @returns {Promise<ArrayBuffer>} Original JPEG file bytes (byte-identical)
 * @throws {Error} If the JXL doesn't contain JPEG reconstruction data or decoding fails
 */
export async function jxlToJpeg(jxlData) {
  const mod = await getModule();

  const input = jxlData instanceof ArrayBuffer
    ? new Uint8Array(jxlData)
    : jxlData;

  // Allocate input buffer in WASM memory
  const inputPtr = mod._malloc(input.length);
  mod.HEAPU8.set(input, inputPtr);

  // Allocate output size pointer
  const sizePtr = mod._malloc(4);

  try {
    const outPtr = mod._jxl_to_jpeg(inputPtr, input.length, sizePtr);

    if (!outPtr) {
      throw new Error(
        'JXL to JPEG reconstruction failed. The JXL file may not contain '
        + 'JPEG reconstruction metadata. Only JXL files created from JPEG '
        + 'sources (via jpegToJxl or cjxl) support this.'
      );
    }

    const outSize = mod.HEAPU32[sizePtr >> 2];
    const result = new ArrayBuffer(outSize);
    new Uint8Array(result).set(mod.HEAPU8.subarray(outPtr, outPtr + outSize));

    mod._jxl_free(outPtr);
    return result;
  } finally {
    mod._free(inputPtr);
    mod._free(sizePtr);
  }
}

/**
 * Pre-initialize the WASM module.
 * Call this early to avoid cold-start latency on first use.
 * @returns {Promise<void>}
 */
export async function init() {
  await getModule();
}
